### PR TITLE
Attempt to fix missing holidayMode in BRP069B4x devices

### LINKED ISSUE #94: Controls not working for models BRP069B4x
Since the last HA Update, the controls for the units with the BRP069B4x adapter model stopped working.
We can still see the Sensor values, but the controls are unavailable. I have other units in my home with the model BRP069C4x and they're working correctly.

I can see this error in the logs:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/daikin_residential/daikin_base.py:116
Integration: Daikin Residential Controller (documentation, issues)
First occurred: October 12, 2022 at 9:44:26 AM (3367 occurrences)
Last logged: 5:50:37 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 812, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 338, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/daikin_residential/climate.py", line 254, in preset_mode
    if self._device.preset_mode_status(mode) == ATTR_STATE_ON:
  File "/config/custom_components/daikin_residential/daikin_base.py", line 170, in preset_mode_status
    return self.getValue(mode)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 116, in getValue
    return data["value"]
KeyError: 'value'

Screenshot 2022-10-14 at 17 49 02
Screenshot 2022-10-14 at 17 51 30

### PR DESCRIPTION
**Pull request by rospogrigio**
Attempt to fix #94:
looks like BRP069B4x  devices lack (or stopped supporting) holidayMode, since this snippet can be found in the json:

```
           "holidayMode": {
            "error": "INVALID_CHARACTERISTIC",
            "ref": "#holidayMode",
            "settable": true,
            "value": {
              "enabled": false,
              "startDate": "2022-03-27T22:00:00Z",
              "endDate": "2022-04-04T21:59:59Z",
              "desiredIsHolidayModeActive": null
            }

```

This PR aims to fix this issue.

### CODE REVIEW

**Comment by gasparhugoricardo** [comment]
Applied the fix and tested successfully! 😄 
Thanks @rospogrigio! Great Work!

**Comment by rospogrigio** [comment]
OK thank you for the feedback. Question: is the away/holiday mode present in your device (I mean, in the Onecta app)? Has it ever worked in HA?

**Comment by gasparhugoricardo** [comment]
I can't see the away/holiday mode anywhere on the Onecta app. Never used it from HA.

**Comment by rospogrigio** [comment]
> I can't see the away/holiday mode anywhere on the Onecta app. Never used it from HA.

Cool, it would be interesting to understand why this issue happened all of a sudden then, probably they changed something cloud-side...

**Comment by VederJay** [comment]
I too can confirm this works!

**Comment by bloddy** [comment]
After trying this patch I get something else .. 

```
Logger: homeassistant.components.climate
Source: custom_components/daikin_residential/daikin_base.py:103
Integration: Climate (documentation, issues)
First occurred: 06:16:38 (1 occurrences)
Last logged: 06:16:38

Error while setting up daikin_residential platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/daikin_residential/climate.py", line 85, in async_setup_entry
    async_add_entities([DaikinClimate(device)], update_before_add=True)
  File "/config/custom_components/daikin_residential/climate.py", line 99, in __init__
    ATTR_SWING_MODE: self._device.swing_modes,
  File "/config/custom_components/daikin_residential/daikin_base.py", line 242, in swing_modes
    hMode = self.getData(ATTR_HSWING_MODE)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 108, in getData
    cmd_set = self.getCommandSet(param)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 103, in getCommandSet
    cmd_set[2] = cmd_set[2].replace("%operationMode%", operation_mode)
TypeError: replace() argument 2 must be str, not None

```


[daikin_residential-368ed263dcdb8390afa59eabd9e005c0-Etaj-1e5a62396941e99fbe15d7a11c7b968d.json(1).txt](https://github.com/rospogrigio/daikin_residential/files/9806201/daikin_residential-368ed263dcdb8390afa59eabd9e005c0-Etaj-1e5a62396941e99fbe15d7a11c7b968d.json.1.txt)

The device, any idea ?

**Comment by rospogrigio** [comment]
Well, this is quite weird. I tested your json data @bloddy and it is working fine; your logs state that the operation_mode is not set but in the json data it appears as currently set to "heating", so I really don't understand which is the problem here.
Anyway, I introduced a further check on the status of the operation_mode, can you please check if it fixes your issue?
Let me know

**Comment by bloddy** [comment]
So if you have any other device that is not available and has the same controller "BRP069B4x" it will bug all your instances that use it.
Fast fix remove the controller that is not seen in onecta, is what I did, and worked with the first patch, right now I don't have another BRP069B4x to check it out ...  when I used the patch I had 2xBRP069B4x, on physical working and another one that it was down for some time ..

**Pull request merged**
