### PR TITLE
Add support for various status flags

### LINKED ISSUE #57: Add all is* flags
Looks not all status flags are exported to HA, some are, but not all. Would be useful to automatically detect errors with the units from within HA

```
                "isCoolHeatMaster": {
                    "settable": false,
                    "value": true
                },
                "isHolidayModeActive": {
                    "settable": false,
                    "value": false
                },
                "isInCautionState": {
                    "settable": false,
                    "value": false
                },
                "isInErrorState": {
                    "settable": false,
                    "value": false
                },
                "isInModeConflict": {
                    "settable": false,
                    "value": false
                },
                "isInWarningState": {
                    "settable": false,
                    "value": false
                },
                "isLockFunctionEnabled": {
                    "settable": false,
                    "value": false
                },
                "isPowerfulModeActive": {
                    "settable": false,
                    "value": false
                },
```

### PR DESCRIPTION
**Pull request by jwillemsen**
Fixes #57

### CODE REVIEW

**Comment by rospogrigio** [comment]
Thank you for your commitment! I believe this creates too many sensors though, may I suggest we regroup some of them in a "Status" sensor, which could show the statuses OK, Error, Warning, Mode Conflict? Also, you have some duplicate code.

**Comment by jwillemsen** [comment]
Ok, looks a good proposal to add a Status sensor for Ok/Error/Warning. I am not sure about Mode Conflict, not sure whether we should combine that

**Comment by rospogrigio** [comment]
> Ok, looks a good proposal to add a Status sensor for Ok/Error/Warning. I am not sure about Mode Conflict, not sure whether we should combine that

I believe that it should be a specific error, and I think it can be raised if you have 2 internal units connected to the same external one, and you set one on Heating and the other to Cooling mode. 
I believe we should combine those as long as we can check that they are mutually exclusive: if, for example, both Mode Conflict and Error can turn to true, then I agree we should keep them separate. Do you agree?

**Comment by jwillemsen** [comment]
I am not sure if combining the multiple flags into one status is easier for the user and there is also no exact documentation from Daikin when they set exactly which flag

**Comment by droscy** [comment]
> I am not sure about Mode Conflict, not sure whether we should combine that [...]
> I believe we should combine those as long as we can check that they are mutually exclusive
> [...] maybe someone can do a test and share the results here

Hello all, I have two internal units with same external one, if I set different modes the second one doesn't switch on, the led blinks fast and the cloud reports `"isInModeConflict": {"settable": false, "value": true}` for that unit only. All the other flags remain `false/00-` both for indoor and outdoor:

    "isInCautionState": {"settable": false, "value": false},
    "isInErrorState": {"settable": false, "value": false},
    "isInWarningState": {"settable": false, "value": false},
    "errorCode": {"settable": false, "value": "00-"},

**Comment by rospogrigio** [comment]
I have the same setup, and the tech that installed it explained me that you can't have the internal units working in different modes, for example one cooling and one heating. He also discouraged using the Auto mode because if you set a temperature close to the external one it may set to (for example) heating mode and then if you request the cooling mode on the other unit you trigger the conflict. Use the same mode on both units and the conflict will disappear.

**Comment by jwillemsen** [comment]
Will have a look to update to a new status sensor with ok/warning/error

**Comment by jwillemsen** [comment]
Could it be that there is an active warning and error, I doubt whether we should combine these flags, if they are mutual exclusive I would expect Daikin to also not use multiple flags

**Comment by jwillemsen** [comment]
@rospogrigio Something to merge to master? As mentioned last year, I think we shouldn't combine flags, just pass the ones provided by Daikin directly to the user

**Pull request closed without merging**
