### PR TITLE
Add network diagnostic entities

### PR DESCRIPTION
**Pull request by droscy**
I've added all network-related gateway data as diagnostic auto-disabled entities. And I've converted the wifi signal strength in a diagnostic entity.

### CODE REVIEW

**Comment by rospogrigio** [comment]
Nice contribution but this PR is removing the Wifi Strength sensor recently added, please restore it...

**Comment by rospogrigio** [comment]
The new diagnostic entities result unavailable to me (I have BRP069C4x devices):
image

Can you check and fix?

**Comment by droscy** [comment]
It is the intended behaviour: these new entities are added disabled by default because most of users probably rarely need them and there is no need to have HA actively monitoring them. If a user needs them, he/she can enable them directly from HA (`Advanced Settings` in entity `Settings` tab).

Advanced Settings

If you prefer having them enabled by default simply remove the following lines from class `DaikinGatewaySensor` during merge (or I can do it in the branch before merge).

    # auto disable these entities when added for the first time
    _attr_entity_registry_enabled_default = False

Side note: the wifi signal strength is enabled in your setup because it was added to HA before these commits and it is already enabled.

**Comment by rospogrigio** [comment]
I see. I am seriously asking myself whether it makes sense to have these info in Sensors since they are values that will never (or rarely) change, and that you can just obtain from the diagnostics.

**Comment by droscy** [comment]
Yes, you are right. The purpose of _diagnostic_ entities is marginal by default but it is harmless to have them and to be disabled.

**Comment by rospogrigio** [comment]
OK, why not. Only thing: I'd leave the wifi strength sensor enabled by default, since it's the only "real" sensor (I mean, with varying values) among these introduced.

**Comment by droscy** [comment]
Ok, I'll change the default for wifi signal.

**Comment by droscy** [comment]
WiFi sensor is now enabled by default

**Pull request merged**
